services:
  - type: web
    name: hebrew-transcription
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: TIMEOUT
        value: 600  # 10 minutes
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        fromService:
          type: web
          name: hebrew-transcription
          property: port
    region: oregon
    branch: main
    healthCheckPath: /
    disk:
      name: whisper-model-cache
      mountPath: /tmp/whisper_model_cache
      sizeGB: 10
    autoDeploy: true
    maxRunTime: 600  # 10 minutes max runtime
